const projectsData = [
  {
    id: 1,
    title: "EcoHub",
    img: "/ecohub.webp",
    alt: "screenshot of EcoHub application",
    desc: "EcoHub was a Figma prototype I created as part of my thesis about user-based design and its effects on programming outcomes. I am now working on making this a fully-working website.",
    aboutProject:
      "This has become a passion project for me. EcoHub front-end is built with React / TypeScript, and the database is made with Firebase. This project also uses firebase for authentication",
    tags: [
      "Figma",
      "React",
      "Redux",
      "Sass",
      "Styled-components",
      "Prop-types",
      "Mui Material",
      "NextUI",
      "Swiper",
      "Firebase Authentication",
      "Firebase Firestore",
    ],
    linktosite: "https://github.com/SebuBergman/EcoHub",
    youtubeID: "PpG7rtFujiA",
    aboutModal:
      "Designed with user-centered principles to enhance accessibility and usability, focusing on engaging, eco-conscious content. Currently expanding EcoHub from prototype to a fully functional website, implementing responsive design, interactive features, and dynamic routing for multiple pages. Added key functionalities such as a web forum, login/register system, and multi-page navigation to create a cohesive user experience. This project is a work in progress, demonstrating commitment to evolving design into a complete, user-friendly product",
    modalLink: "Visit Github",
    imageSize: "100%",
  },
  {
    id: 2,
    title: "RAG Agent",
    img: "/rag_agent.webp",
    alt: "screenshot of The RAG Agent application",
    desc: "Built a RAG (Retrieval-Augmented Generation) agent using Python, FastAPI, Hugging Face, and OpenAI. Processes PDFs, performs semantic search with MongoDB embeddings, and delivers real-time, context-aware answers through a front-end interface.",
    aboutProject:
      "This project was built with Python, FastAPI, MongoDB and React / TypeScript (frontend), and OpenAI API integration.",
    tags: [
      "React",
      "TypeScript",
      "Python",
      "FastAPI",
      "MongoDB",
      "Amazon S3",
      "Retrieval-Augmented Generation",
      "Hugging Face Transformers",
      "OpenAI API",
      "Semantic Search / Embeddings",
      "Keyword Searach",
      "Document Upload",
      "PDF Processing",
      "Langchain",
      "Axios",
    ],
    linktosite: "https://github.com/SebuBergman/RAG-Project-frontend",
    youtubeID: "",
    aboutModal:
      "Developed a Retrieval-Augmented Generation (RAG) agent using Python, FastAPI, Hugging Face, and OpenAI. The system processes uploaded PDFs—stored in Amazon S3—by splitting them into sentences and generating embeddings via Hugging Face’s sentence transformer API. It performs semantic search over these embeddings using MongoDB, retrieving relevant context to generate accurate, real-time answers with OpenAI. A front-end interface allows seamless user interaction through a RESTful API.",
    modalLink: "Visit Github",
    imageSize: "75%",
  },
  {
    id: 3,
    title: "Email Assistant",
    img: "/email_assistant.webp",
    alt: "screenshot of The email assistant application",
    desc: "A GenAI-powered app for rewriting and summarizing emails in tones like professional, friendly, or persuasive. Built with FastAPI, React, TypeScript, and OpenAI integration. Features advanced prompt engineering for tone control and email intent recognition.",
    aboutProject:
      "This project was built with Python, FastAPI, React, TypeScript, and OpenAI API integration.",
    tags: ["React", "TypeScript", "Python", "FastAPI", "OpenAI API", "Axios"],
    linktosite: "",
    youtubeID: "",
    aboutModal:
      "This GenAI-powered app rewrites and summarizes emails in user-selected tones such as professional, friendly, and persuasive. Built with FastAPI, React, TypeScript, and OpenAI integration, it features advanced prompt engineering to ensure precise tone control and intent recognition. A seamless, productivity-enhancing tool for email communication.",
    modalLink: "Visit Github",
    imageSize: "80%",
  },
  {
    id: 4,
    title: "avone.fi",
    img: "/avone.webp",
    alt: "screenshot of avone.fi application",
    desc: "avone.fi is a website for a Finnish entrepreneur who offers WordPress development & maintenance, website creation, newsletter & SEO optimization services",
    aboutProject:
      "This website was built on Wordpress. Just a simple one page website",
    tags: ["WordPress", "Bootstrap", "HTML", "CSS"],
    linktosite: "https://www.avone.fi",
    youtubeID: "",
    aboutModal:
      "avone.fi is a website for a Finnish entrepreneur who offers WordPress development & maintenance, website creation, newsletter & SEO optimization services",
    modalLink: "Visit site",
    imageSize: "90%",
  },
  {
    id: 5,
    title: "tukikeskustelut.com",
    img: "/tukikeskustelut.webp",
    alt: "screenshot of tukikeskustelut.fi application",
    desc: "Tukikeskustelut is a website for a Finnish entrepreneur who offers brief therapy, work counselling and crisis work & NUOTTI coaching as a services",
    aboutProject:
      "The website is built on Wordpress using bootstrap for extra styling",
    tags: ["WordPress", "Bootstrap", "HTML", "CSS"],
    linktosite: "https://www.tukikeskustelut.com",
    youtubeID: "",
    aboutModal:
      "Tukikeskustelut is a website for a Finnish entrepreneur who offers brief therapy, work counselling and crisis work & NUOTTI coaching as a services",
    modalLink: "Visit site",
    imageSize: "90%",
  },
  {
    id: 6,
    title: "Mint",
    img: "/Mint.webp",
    alt: "screenshot of mint web application",
    desc: "With a ”Tinder for jobs” approach, anonymized and values-based matching, and well-being alerts for companies, MINT fosters transparency and mental wellness in hiring.",
    aboutProject:
      "Built (and designed) at Junction Hackathon 2024 in 3 days, MINT matches job seekers with companies prioritizing mental health, inclusion, and growth",
    tags: [
      "React",
      "TypeScript",
      "Redux",
      "Firebase",
      "MongoDB",
      "Python (FastAPI)",
    ],
    linktosite: "https://github.com/J24-Cobalt/front-end",
    youtubeID: "3nbMg8a8-DU",
    aboutModal:
      "Mint was a project we developed for the Junction Hackathon 2024 over the course of three days. We began with simple paper prototyping, then moved on to designing the UI. Our tech stack included a FastAPI (python) backend and a React/TypeScript frontend, where we built a rudimentary Redux store to manage state and fetch data from the backend API. Additionally, we implemented a Tinder-like swiping feature for job positions and job applicants.",
    modalLink: "Visit github",
    imageSize: "100%",
  },
  {
    id: 7,
    title: "Music player",
    img: "/sebmusic_player.webp",
    alt: "screenshot of music player application",
    desc: "My music player app lets you search and play songs via the Deezer API. Features include song playback, a 'radio' mode for random tracks, genre filtering, song search, and favoriting. Built with React, JavaScript, and styled-components for sleek UI design.",
    aboutProject:
      "This music player was built with React, JavaScript, and styled-components.",
    tags: [
      "React",
      "JavaScript",
      "Axios",
      "styled-components",
      "Deezer API",
      "Axios",
    ],
    linktosite: "https://github.com/SebuBergman/Seb-Music",
    youtubeID: "",
    aboutModal:
      "My music player app allows users to search and play songs using the Deezer API. Key features include seamless playback, a 'radio' mode that plays random tracks, genre-based filtering, and a search function to find songs by name. Users can also like their favorite tracks for quick access. The frontend is built with React and JavaScript, styled with styled-components for a modern, responsive design. The app delivers a smooth listening experience with intuitive controls and dynamic music discovery.",
    modalLink: "Visit github",
    imageSize: "85%",
  },
  {
    id: 8,
    title: "leffakirjasto",
    img: "/leffakirjasto.webp",
    alt: "screenshot of leffakirjasto application",
    desc: "This is a personal project for a android app which you can add movies and tv shows to a firebase firestore and search for movies using the MovieDB API.",
    aboutProject: "This app was built with React Native for android",
    tags: ["React Native", "TypeScript", "Redux", "Firebase", "Expo"],
    linktosite: "https://github.com/SebuBergman/leffakirjasto",
    youtubeID: "dtqt1ruM7eE",
    aboutModal:
      "This personal project is an Android app built with React Native. It allows users to search for movies using the MovieDB API and add them to a Firebase Firestore database. Additionally, users can add TV shows, specify a custom number of seasons, and keep track of their ownership status",
    modalLink: "Visit github",
    imageSize: "100%",
  },
];

export default projectsData;
